---
apiVersion: v1
data:
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXk=
  REDMINE_DB_PASSWORD: dGVzdHBhc3N3b3Jk
kind: Secret
metadata:
  name: my-secret
  namespace: gb4
type: Opaque

